Na tarefa de hoje, fiquei responsável pelos testes do módulo "html_bloco_lista_de_usuarios.py".
Após a primeira execução dos testes, o erro a seguir foi encontrado:

 File testes/html_bloco_lista_de_usuarios_TST.py, line 28, in testa ** erro em testa(gera.N): name 'bloco_texto' is not defined 

Analisando os logs de erro, foi possível observar que o erro estava no módulo "html_bloco_usuario". 
Ao acessar o arquivo, foi possível observar que a geração de blocos de texto estava errada, o módulo "html_bloco_texto" não estava sendo importado corretamente, nem sua função de geração estava sendo chamada.

Ao executar o teste novamente, o erro encontrado foi:

  File "/Users/diegokamiha/Documents/MC857/2020-05-08/Projeto-MC857-2020-1/usuario.py", line 97, in busca_por_identificador
    return usuario_IMP.busca_por_identificador(id_usuario)
  File "/Users/diegokamiha/Documents/MC857/2020-05-08/Projeto-MC857-2020-1/usuario_IMP.py", line 94, in busca_por_identificador
    assert type(usr) is usuario.Objeto_Usuario

Após um pouco de debug de código, descobri que "usr" era retornado como "None", o que significa que não existe registro na tabela com o id dado.

Os registros criados no banco sao:
usuário U-00000001 = "José Primeiro" criado
usuário U-00000002 = "João Segundo" criado
usuário U-00000003 = "Juca Terceiro" criado

O arquivo de teste buscava por:
usr1_ident = "U-00000001"
usr2_ident = "U-00000002"
usr5_ident = "U-00000005"

Alterando o usr5_ident para um usr3_ident de valor "U-00000003" foi possível executar o teste completo.
