ISSUE 196858:
[A] "Checar objeto"(id="U-00000001") > "Ver poltronas": não funciona.

------------------------------------------
Para fazer a tarefa hoje, tive que logar antes como adminstrador da loja terceiro@gmail.com, senha 333333333).

Quando tento chegar o objeto de id "U-00000001" e clico no botão "Ver Poltronas", tenho a seguinte resposta: 

ERRO: "Não foi possível completar a operação. Erro: ** comando ver poltronas ainda não implementado"

Se eu tento outro id, por exemplo "U-00000002" ou "U-00000003", também não consigo.

Creio que o comando_ver_poltronas.py esteja com problemas. Rodei o comando_ver_poltronas_TST.py e sem erros.
------------------------------------------

1) Modulo alterado:

	* processa_comando_http_IMP.py:

Primeiramente, nesse módulo percebi que o comando tava chamando um html de erro diretamente e por isso não tava chamando o comando_ver_poltrona.

    elif cmd == '/ver_poltronas':
      # Usuário apertou o botão "ver poltronas" ou equivalente:
      pag =  html_pag_mensagem_de_erro.gera(ses, ("** comando ver poltronas ainda não implementado"))

Desse modo, troquei essa linha e chamei o comando_ver_poltrona.

    elif cmd == '/ver_poltronas':
      # Usuário apertou o botão "ver poltronas" ou equivalente:
      pag = comando_ver_poltrona.processa(ses, args)

Para fazer a chamada, foi necessário importar comando_ver_poltrona dando "import comando_ver_poltrona".

Rodei o servidor e, ao invés dar o comando, a página dava erro. Vi no terminal que o erro estava presente em comando_ver_poltrona_IMP.py.


	* comando_ver_poltrona_IMP.py:

O terminal acusava a seguinte exceção:

"Exception happened during processing of request ... KeyError: 'id_user'" na linha 16.

A linha 16 era dada por: 
	ids_compras = compra.busca_por_cliente(args['id_user'])

O argumento que estávamos passando (um dicionário) era dado por: {'id': 'U-00000001'}

Então percebi que havia um erro de escrita, pois estávamos passando 'id_user' ao invés de 'id'.

Então mudei a linha 16 para: 
	ids_compras = compra.busca_por_cliente(args['id'])

Após fazer essa mudança, o botão "Ver poltronas" funcionava perfeitamente! 

2) Teste do módulos: 

	* comando_ver_poltrona_TST.py:

Rodei o comando de test e ele falhou na primeira vez:

"File comando_ver_poltrona_TST.py, line 32, in testa ** erro em testa(processa.teste): 'id'

Nessa hora, falei com o professor se eu deveria usar 'id' ou 'id_user'. Como deixou opcional, optei por utilizar 'id'.

Assim, também mudei o arquivo teste. Mudei a linha 34 de:

	testa('teste', ses, {'id_user': 'U-00000001'})

Para:

	testa('teste', ses, {'id': 'U-00000001'})

Rodei de novo e o teste rodou sem erros!